export const actionType = {
  GET_FEATURED_PRODUCTS: "GET_FEATURED_PRODUCTS",
  GET_FEATURED_PRODUCTS_SUCCESS: "GET_FEATURED_PRODUCTS_SUCCESS",
  REGISTER_USER:'REGISTER_USER',
  REGISTER_USER_SUCCESS:'REGISTER_USER_SUCCESS'
};
