export const fakeData = {
  featuredProducts: [
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
    {
      discount: "-7%",
      productName: "Sapien Libero",
      star: 4,
      oldPrice: 74.0,
      newPrice: 69.0,
    },
  ],
};
